/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Usuario;

import Controlador.ConexionBADA;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class EstadisticaUsuario extends javax.swing.JPanel {
    
    ConexionBADA con=new ConexionBADA();
    DefaultTableModel modelo = new DefaultTableModel();
    public EstadisticaUsuario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTextField1 = new javax.swing.JTextField();
        lblporcentaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstadistica = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        bprogress = new javax.swing.JProgressBar();
        lblufondo = new javax.swing.JLabel();
        lblusuarioEs = new javax.swing.JLabel();
        lblporcentBADA = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        jTextField1.setText("jTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblporcentaje.setBackground(new java.awt.Color(0, 0, 0));
        lblporcentaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(lblporcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 50, 30));

        jtEstadistica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtEstadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEstadisticaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEstadistica);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 420, 97));

        btnBuscar.setText("MOSTRAR DATOS Y ESTADISTICAS");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 300, -1));

        bprogress.setBackground(new java.awt.Color(255, 51, 51));
        bprogress.setForeground(java.awt.Color.green);
        bprogress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        bprogress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(bprogress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 420, 50));

        lblufondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FondoEstadistica.jpeg"))); // NOI18N
        add(lblufondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 490));

        lblusuarioEs.setForeground(new java.awt.Color(255, 255, 255));
        add(lblusuarioEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 90, 20));

        lblporcentBADA.setForeground(new java.awt.Color(255, 255, 255));
        lblporcentBADA.setText("jLabel2");
        add(lblporcentBADA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 20, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        InicioUsuario a=new InicioUsuario();
        String campo=a.lblUsuarioJ.getText();
        System.out.println(campo);
        
            try {
                DefaultTableModel modelo = new DefaultTableModel();
                jtEstadistica.setModel(modelo);

                PreparedStatement ps = null;
                ResultSet rs = null;
                Connection conn = con.getCon();
                String b="baja";
                String sql = "SELECT codJuego,codPreguntas, usuarioJ, estadistica FROM juego WHERE usuarioJ LIKE '"+lblusuarioEs.getText()+"'";
                System.out.println(sql);
                ps = conn.prepareStatement(sql);
                rs = ps.executeQuery();
                


                ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
                int cantidadColumnas = rsMd.getColumnCount();

                modelo.addColumn("Código");
                modelo.addColumn("Preguntas");
                modelo.addColumn("Usuario");
                modelo.addColumn("Estadistica");
                int[] anchos = {50, 200, 50, 50};
                for (int i = 0; i < jtEstadistica.getColumnCount(); i++) {
                    jtEstadistica.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }

                while (rs.next()) {
                    Object[] filas = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        filas[i] = rs.getObject(i + 1);
                    }
                    modelo.addRow(filas);
                }

            } catch (Exception ex) {
                System.err.println(ex.toString());
            }
            
            porcentaje();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jtEstadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEstadisticaMouseClicked
      
    }//GEN-LAST:event_jtEstadisticaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bprogress;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable jtEstadistica;
    private javax.swing.JLabel lblporcentBADA;
    private javax.swing.JLabel lblporcentaje;
    private javax.swing.JLabel lblufondo;
    public javax.swing.JLabel lblusuarioEs;
    // End of variables declaration//GEN-END:variables

    public void ingresarvalor(){
        int valor=Integer.parseInt(lblporcentBADA.getText());
        bprogress.setValue((int) valor);
        lblporcentaje.setText(valor+"%");
    }
    
    public void porcentaje(){
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection conn = con.getCon();
            String sql = "SELECT  estadistica FROM juego WHERE usuarioJ LIKE '"+lblusuarioEs.getText()+"'";
            System.out.println(sql);
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            int suma=0;
            
            while(rs.next()){ 
               int p=rs.getInt("estadistica");
                suma =suma+p;
                System.out.println(suma);
            }
            
            PreparedStatement ps1=null;
            ResultSet rs1 = null;
            String sql1 = "SELECT COUNT(estadistica) AS Total FROM juego WHERE usuarioJ LIKE '"+lblusuarioEs.getText()+"'";
            System.out.println(sql1);
            ps1= conn.prepareStatement(sql1);
            rs1 = ps1.executeQuery();
            int total=0;
            while(rs1.next()){
                total=rs1.getInt("Total");
            }
            if (total==0) {
                JOptionPane.showMessageDialog(null, "El usuario no registra datos");
                
            }else{
                System.out.println("total "+total);
                System.out.println("Suma "+suma);
                int porcentaje=((suma*100)/(total*100));
                System.out.println(porcentaje);
            
                lblporcentBADA.setText(String.valueOf(porcentaje));
                ingresarvalor(); 
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(EstadisticaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
