/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Usuario;

import Consultas.ConsultasSQL;
import Controlador.ConexionBADA;
import Interfaz.Preguntas;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Usuario
 */
public class JuegosUsuario extends javax.swing.JPanel {
 ConexionBADA conecta=new ConexionBADA();
    public JuegosUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnirjuego = new javax.swing.JButton();
        lblusuarioirJ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/3613527513_40e75848-dfdc-4124-af21-1560b279d45c.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 313, 258));

        btnirjuego.setText("IR AL JUEGO");
        btnirjuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnirjuegoActionPerformed(evt);
            }
        });
        jPanel1.add(btnirjuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 158, 78));
        jPanel1.add(lblusuarioirJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 42, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FondoJuegos.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnirjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnirjuegoActionPerformed
       
//        InicioUsuario i=new InicioUsuario();
//       i.cerrar();
        Irusuario();
       
    }//GEN-LAST:event_btnirjuegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnirjuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JLabel lblusuarioirJ;
    // End of variables declaration//GEN-END:variables
    public void Irusuario(){
        Preguntas pregunta=new Preguntas();
         pregunta.setVisible(true);
         String usu=lblusuarioirJ.getText();
         pregunta.lblusuario.setText(usu);
    }

}