
package IngresoImagen;

import Controlador.ConexionBADA;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class JFinsertarAudio extends javax.swing.JFrame {

    CPreguntas vo=new CPreguntas();
    AudioIA dao=null;
    ConexionBADA conecta=new ConexionBADA();
    
    public JFinsertarAudio() {
        initComponents();
        this.setLocationRelativeTo(null);
//        this.setTitle("INGRESO DE AUDIOS");
//        grabarimagenes();
    }

//    public void grabarimagenes(){
//        try {
//            String sql="SELECT codImagen FROM imagen";
//            ResultSet rs=conecta.query(sql);
//            cmbBox.removeAllItems();
//            
//            while (rs.next()) {
//                
//                try {
//                    cmbBox.addItem(rs.getString(1));
//                } catch (SQLException ex) {
//                    Logger.getLogger(JFinsertarAudio.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(JFinsertarAudio.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtnombreaudio = new javax.swing.JTextField();
        ElegirArchivo = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        txtruta = new javax.swing.JLabel();
        btnvoz = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        txtpregunta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtrespuesta = new javax.swing.JTextField();
        txtcodpregunta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcodimagen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 43));
        jPanel1.add(txtnombreaudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 215, 30));

        ElegirArchivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ElegirArchivo.setText("Elegir Archivo");
        ElegirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(ElegirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 130, 30));

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, 30));

        txtruta.setBackground(new java.awt.Color(0, 0, 0));
        txtruta.setForeground(new java.awt.Color(255, 255, 255));
        txtruta.setText("RUTA");
        txtruta.setBorder(new javax.swing.border.MatteBorder(null));
        txtruta.setOpaque(true);
        jPanel1.add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 330, 30));

        btnvoz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IngresoImagen/voz.png"))); // NOI18N
        btnvoz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(btnvoz, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 110, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Respuesta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pregunta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btnGuardar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 390, 110, 40));
        jPanel1.add(txtpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ruta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 47, 23));
        jPanel1.add(txtrespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 30));
        jPanel1.add(txtcodpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Imagen");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Codigo Pregunta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(txtcodimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IngresoImagen/FondoImagen.png"))); // NOI18N
        jLabel3.setText("Codigo de pregunta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ElegirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirArchivoActionPerformed

        JFileChooser j=new JFileChooser();
        j.setCurrentDirectory(new File("C:\\Users\\Usuario\\OneDrive\\Documentos\\Audios.wav"));
        FileNameExtensionFilter f=new FileNameExtensionFilter("mp3, wav & flac","mp3","wav","flac");
        
        int s=j.showOpenDialog(this);
        if (s==JFileChooser.APPROVE_OPTION) {
            
            String ruta=j.getSelectedFile().getAbsolutePath();
            String name=j.getSelectedFile().getName();
            txtruta.setText(ruta);
            txtnombreaudio.setText(name);
           
        }
      

    }//GEN-LAST:event_ElegirArchivoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        String codpregunta=txtcodpregunta.getText();
        String pregunta=txtpregunta.getText();
        String codImagen=txtcodimagen.getText();
        String respuesta=txtrespuesta.getText();
        File ruta=new File(txtruta.getText());
        agregar(codpregunta, pregunta, codImagen, respuesta, ruta);
        limpiar();
        JOptionPane.showMessageDialog(null, "Guardado");
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    public void limpiar(){
      txtnombreaudio.setText("");
      txtcodpregunta.setText("");
      txtpregunta.setText("");
      txtrespuesta.setText("");
      txtruta.setText("");
      txtcodimagen.setText("");
    }
    
//    public int combxpregunta(){
//        try {
//            String sql="SELECT COUNT(codImagen) FROM imagen";
//            ResultSet rs=conecta.query(sql);
//            String a=rs.getString("codImagen");
//            int b=Integer.valueOf(a);
//            System.out.println(b);
//            for (int num = 0; num <=b; num++) {
//                if(num==cmbBox.getSelectedIndex()) {
//                    return num;
//                }
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(JFinsertarAudio.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return 0;
//    }
    public void agregar(String codpregunta,String pregunta,String codImagen,String respuesta, File ruta){
        
        dao=new AudioIA();
        vo.setCodigoPregunta(Integer.parseInt(codpregunta));
        vo.setPregunta(pregunta);
        vo.setCodImagen(codImagen);
        vo.setRespuesta(respuesta);        
               
        try {
            byte[] audio=new byte[(int) ruta.length()];
            InputStream i=new FileInputStream(ruta);
            i.read(audio);
            vo.setArchivoaudio(audio);
        } catch (Exception e) {
            vo.setArchivoaudio(null);
        }
        dao.Agregar_Audio(vo);
        limpiar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFinsertarAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFinsertarAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFinsertarAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFinsertarAudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFinsertarAudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ElegirArchivo;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvoz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcodimagen;
    private javax.swing.JTextField txtcodpregunta;
    private javax.swing.JTextField txtnombreaudio;
    private javax.swing.JTextField txtpregunta;
    private javax.swing.JTextField txtrespuesta;
    private javax.swing.JLabel txtruta;
    // End of variables declaration//GEN-END:variables

}
