
package Interfaz;

import Consultas.ConsultasSQL;
import Controlador.ConexionBADA;
import Interfaz.Usuario.InicioUsuario;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Usuario
 */
public class Preguntas extends javax.swing.JFrame {
   
   ConexionBADA conecta=new ConexionBADA();
   
   ImageIcon imagen1[]=new ImageIcon[11];
   
//   int contador;

 FondoPanel fondo=new FondoPanel();
 
    public Preguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("YUPAYKUNA--LOS NUMEROS");
        for (int i = 1; i <11; i++) {
            imagen1[i]=new ImageIcon(getClass().getResource("/ImagenesJuegoN1/Numero"+i+".png")); 
        }
            lblImagenSalida.setIcon(imagen1[1]);
       
    }
    
    
    class FondoPanel extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Recursos/ImagenJuegos.jpeg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new FondoPanel();
        lblPreguntas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        radio2 = new javax.swing.JRadioButton();
        radio1 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        btnSalirjuego = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        lblImagenSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 513));

        lblPreguntas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblPreguntas.setText("Pregunta");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio2);
        radio2.setText("Hola");

        buttonGroup1.add(radio1);
        radio1.setText("jRadioButton2");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio3);
        radio3.setText("jRadioButton3");

        btnSalirjuego.setText("Salir");
        btnSalirjuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirjuegoActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirjuego, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagenSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radio1)
                                    .addComponent(radio2)
                                    .addComponent(radio3))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagenSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio3)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(btnSalirjuego, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirjuegoActionPerformed
       InicioUsuario inicio=new InicioUsuario();
       inicio.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSalirjuegoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random rd=new Random();
        int numero;
        numero=(rd.nextInt(10-2)); 
        if (numero==0) {
            numero=numero+1;
            
        }
        System.out.println(numero);
        
        String sql="SELECT preguntas.pregunta, preguntas.Respuesta,imagen.imagen FROM preguntas, imagen WHERE preguntas.codPregunta LIKE '"+numero+"';";
//        System.out.println(numero.Random());
        ResultSet rs;
        ImageIcon foto= conecta.getFoto(Integer.valueOf(numero));
        InputStream is=null;
        ImageIcon ii=null ;
        ConsultasSQL consulta=new ConsultasSQL(conecta.getCon(), sql);
        if(consulta.getError()==null){
                rs=consulta.getResultado();
                try {
                    rs.next();
                    String pregunta = rs.getString("pregunta");
                    lblPreguntas.setText(pregunta);
                    String respuesta=rs.getString("Respuesta");
                    radio1.setText(respuesta);
                    if(foto!=null){
                        lblImagenSalida.setIcon(foto);
                    }else{
                        lblImagenSalida.setIcon(null);
                    }
                    lblImagenSalida.updateUI();
                    
                } catch (SQLException ex) {
                    ex.getMessage();
                }
            }

        lblImagenSalida.setIcon(imagen1[numero]);
        
        Random r=new Random();
        int num;
        num=(r.nextInt(20-2)); 
        if (num==0) {
            num=num+1; 
        }
        
        Random a=new Random();
        int n;
        n=(a.nextInt(20-2)); 
        if (n==0) {
            n=n+1; 
        }
        ramdonPreguntas(num,n);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
//       
         int numero=0;
        lblImagenSalida.setIcon(imagen1[numero]);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1ActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalirjuego;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblImagenSalida;
    public javax.swing.JLabel lblPreguntas;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    // End of variables declaration//GEN-END:variables

    public void ramdonPreguntas(int num1, int num2){
        Map<Integer, String> treeMap = new TreeMap<Integer, String>();
            treeMap.put(1, "PICHKA CHUNKA");        treeMap.put(7, "CHUSKU CHUNKA");
            treeMap.put(2, "PATSAK");               treeMap.put(8, "CHUNKA PUSAK");
            treeMap.put(3, "HUNU");                 treeMap.put(9, "PUSAK PATSAK");
            treeMap.put(4, "SUKTA PATSAK");         treeMap.put(10, "CHUNKA SHUK");
            treeMap.put(5, "WARANKA");              treeMap.put(11, "TAWA CHUNKA");
            treeMap.put(6,"CHUSKU PATSAK");
            treeMap.put(12, "SUKTA CHUNKA");        treeMap.put(18, "CHUNKA PISQAYOP");
            treeMap.put(13, "CHUNKA PUSAK");        treeMap.put(19, "QANCHIS CHUNKA");
            treeMap.put(14, "ISHKAY CHUNKA");       treeMap.put(20, "PUSAQ CHUNKA");
            treeMap.put(15, "PUSAK CHUNKA");          
            treeMap.put(16, "CHUNKA SHUK");         
            treeMap.put(17,"KIMSA PATSAK");
                
                    
                    Iterator<Integer> it = treeMap.keySet().iterator();
                    while(it.hasNext()){
                    Integer key = it.next();
                    if (key==num1) {
                        radio2.setText(treeMap.get(key));
                    }
                    if (key==num2) {
                         radio3.setText(treeMap.get(key));   
                    }
                }
                   
            }
}
