/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Consultas.ConsultasSQL;
import Controlador.ConexionBADA;
import Modelo.Usuario;
import Modelo.cTraductor;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Normalizer;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Traductor extends javax.swing.JFrame {
    ConexionBADA conecto= new ConexionBADA();
    Usuario usuario=new Usuario();
    public static ArrayList<cTraductor> lista= new ArrayList();
    FondoPanel ab=new FondoPanel();
    public Traductor() {
        this.setContentPane(ab);
        initComponents();
        this.setLocationRelativeTo(null);
    }
class FondoPanel extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Recursos/Pantalla Traductor.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        cbxelegiridima = new javax.swing.JComboBox<>();
        btnJuego = new javax.swing.JButton();
        btnTraduccir = new javax.swing.JToggleButton();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        txtPalabraIngreso = new javax.swing.JTextField();
        lblTraduccion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablahistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 628));

        cbxelegiridima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Traduccion", "Español-kichwa", "Kichwa-Español" }));
        cbxelegiridima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxelegiridimaActionPerformed(evt);
            }
        });

        btnJuego.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnJuego.setText("JUEGOS");
        btnJuego.setToolTipText("JUEGOS");
        btnJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoActionPerformed(evt);
            }
        });

        btnTraduccir.setText("TRADUCIR");
        btnTraduccir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraduccirActionPerformed(evt);
            }
        });

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        txtPalabraIngreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPalabraIngreso.setToolTipText("Traduccion");

        lblTraduccion.setBackground(new java.awt.Color(51, 204, 0));
        lblTraduccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTraduccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("HISTORIAL");

        tablahistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Palabra", "Traduccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablahistorial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addGap(193, 193, 193))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPalabraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxelegiridima, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJuego))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(lblTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(btnTraduccir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse)
                    .addComponent(btnIniciarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPalabraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxelegiridima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnTraduccir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxelegiridimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxelegiridimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxelegiridimaActionPerformed

    private void btnJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoActionPerformed
       LogIn login=new LogIn();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnJuegoActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        this.setVisible(false);
        Registro r1=new Registro();
        r1.setVisible(true);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        LogIn l1=new LogIn();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnTraduccirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraduccirActionPerformed
        
            
            

        if (txtPalabraIngreso.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese una palabra");
        }else{
            if (comboBox()==0) {
            JOptionPane.showMessageDialog(null, "Elige los idimas al que desea traducir");
            } else {
                if (comboBox()==1) {
                    Es_Ki();
                    enviarDatos();
                } else {
                    Ki_Es();
                    enviarDatos();
                }
            }
        }
      
        
    }//GEN-LAST:event_btnTraduccirActionPerformed
     
   public void enviarDatos(){
       cTraductor traduce=new cTraductor();
        lista.add(traduce);
        String palabraing=txtPalabraIngreso.getText();
        String paltraduccion=lblTraduccion.getText();
        traduce.setPalabraingreso(palabraing);
        traduce.setPalabrasalida(paltraduccion);
        mostrar();
   }
    
    public void mostrar(){
   
        String matriz[][]=new String [lista.size()][2];
        for(int i=0; i<lista.size(); i++){
//            personas p1 = (personas)apersona.get(i);
            matriz[i][0]=lista.get(i).getPalabraingreso();
            matriz[i][1]=lista.get(i).getPalabrasalida();
            
            tablahistorial.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Palabra Ingreso", "Traduccion"
            }
        ));
       
   
        }
               
    }
    public static String cleanString(String texto) {
        texto = Normalizer.normalize(texto, Normalizer.Form.NFD);
        texto = texto.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "");
        return texto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnJuego;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JToggleButton btnTraduccir;
    private javax.swing.JComboBox<String> cbxelegiridima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTraduccion;
    private javax.swing.JTable tablahistorial;
    private javax.swing.JTextField txtPalabraIngreso;
    // End of variables declaration//GEN-END:variables

    public int comboBox(){
        int num=cbxelegiridima.getSelectedIndex();
        if (num==0) {
            return 0;
        } else {
            if (num==1) {
                return 1;
            } else {
                return 2;
            }
        }
    }
    
    
    public void Es_Ki(){
        String camb=txtPalabraIngreso.getText().toLowerCase();
        String nw=cleanString(camb);
        String cnw=nw.replace("ñ","~n");//esto aun no funciona 
        System.out.println(cnw);
        String codigo="SELECT codpalabra2 From palabra1 WHERE palabra1p='"+cnw+"'";
        
            ResultSet rsc,rsp;
            ConsultasSQL con = new ConsultasSQL(conecto.getCon(), codigo);
            
            if(con.getError()==null){
                rsc=con.getResultado();
                try {
                    rsc.next();
                    String coigo2 = rsc.getString("codpalabra2");
                    String palabra="SELECT palabra2p FROM palabra2 WHERE codPalabra2='"+coigo2+"'";
                    ConsultasSQL pal=new ConsultasSQL(conecto.getCon(), palabra);
                    rsp=pal.getResultado();
                    rsp.next();
                    String palabraesp = rsp.getString("palabra2p");
                    lblTraduccion.setText(palabraesp);
                   rsp.close();
                    
                } catch (SQLException ex) {
                    ex.getMessage();
                    lblTraduccion.setText(txtPalabraIngreso.getText());
                }
                
               
            }
    }
    
    public void Ki_Es(){
        String camb=txtPalabraIngreso.getText().toLowerCase();
        String nw=cleanString(camb);
        String cnw=nw.replace("ñ","~n");//esto aun no funciona 
        System.out.println(cnw);
        String codigo="SELECT codPalabra2 FROM palabra2 WHERE palabra2p='"+cnw+"'";
        
            ResultSet rsc,rsp;
            ConsultasSQL con = new ConsultasSQL(conecto.getCon(), codigo);
            
            if(con.getError()==null){
                rsc=con.getResultado();
                try {
                    rsc.next();
                    String coigo2 = rsc.getString("codPalabra2");
                    String palabra="SELECT palabra1p FROM palabra1 WHERE codpalabra2='"+coigo2+"'";
                    ConsultasSQL pal=new ConsultasSQL(conecto.getCon(), palabra);
                    rsp=pal.getResultado();
                    rsp.next();
                    String palabraesp = rsp.getString("palabra1p");
                    lblTraduccion.setText(palabraesp);
                } catch (SQLException ex) {
                    ex.getMessage();
                    lblTraduccion.setText(txtPalabraIngreso.getText());
                }
            }
    }
}
