/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Consultas.ConsultasSQL;
import Controlador.ConexionBADA;
import static Interfaz.Traductor.cleanString;
import static Interfaz.Traductor.lista;
import Interfaz.Usuario.InicioUsuario;
import Modelo.cTraductor;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class TraductorlogIn extends javax.swing.JFrame {
    ConexionBADA conecto=new ConexionBADA();
     public static ArrayList<cTraductor> lista= new ArrayList();
   FondoPanel a=new FondoPanel();
   

    public TraductorlogIn() {
        this.setContentPane(a);
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    class FondoPanel extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Recursos/Pantalla Traductor.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new FondoPanel();
        cbxelegiridima = new javax.swing.JComboBox<>();
        btnTraduccir = new javax.swing.JToggleButton();
        txtPalabraIngreso = new javax.swing.JTextField();
        lblTraduccion = new javax.swing.JLabel();
        lblnombresUT = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblusuarioT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTrad = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 826));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        cbxelegiridima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Traduccion", "Español-kichwa", "Kichwa-Español" }));
        cbxelegiridima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxelegiridimaActionPerformed(evt);
            }
        });

        btnTraduccir.setText("TRADUCIR");
        btnTraduccir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraduccirActionPerformed(evt);
            }
        });

        txtPalabraIngreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPalabraIngreso.setToolTipText("Traduccion");

        lblTraduccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTraduccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblTraduccion.setPreferredSize(new java.awt.Dimension(1000, 628));

        lblnombresUT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblusuarioT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tableTrad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Palabra", "Traduccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTrad);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("HISTORIAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblusuarioT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnombresUT, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrarSesion)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 155, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPalabraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxelegiridima, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTraduccir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(408, 408, 408))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(340, 340, 340))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(398, 398, 398))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblnombresUT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPerfil)
                        .addComponent(btnCerrarSesion))
                    .addComponent(lblusuarioT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPalabraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxelegiridima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTraduccir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxelegiridimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxelegiridimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxelegiridimaActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Traductor traductor=new Traductor();
        traductor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
   InicioUsuario perfil=new InicioUsuario();
    private void btnTraduccirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraduccirActionPerformed
        if (txtPalabraIngreso.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese una palabra");
        }else{
            if (comboBox()==0) {
            JOptionPane.showMessageDialog(null, "Elige el idioma al que desea traducir");
            } else {
                if (comboBox()==1) {
                    Es_Ki();
                    enviarDatos();
                } else {
                    Ki_Es();
                    enviarDatos();
                }
            }
        }
      
    }//GEN-LAST:event_btnTraduccirActionPerformed

     public void enviarDatos(){
       cTraductor traduce=new cTraductor();
        lista.add(traduce);
        String palabraing=txtPalabraIngreso.getText();
        String paltraduccion=lblTraduccion.getText();
        traduce.setPalabraingreso(palabraing);
        traduce.setPalabrasalida(paltraduccion);
        mostrar();
   }
     
    public void mostrar(){
   
        String matriz[][]=new String [lista.size()][2];
        for(int i=0; i<lista.size(); i++){
//            personas p1 = (personas)apersona.get(i);
            matriz[i][0]=lista.get(i).getPalabraingreso();
            matriz[i][1]=lista.get(i).getPalabrasalida();
            
            tableTrad.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Palabra Ingreso", "Traducción"
            }
        ));
       
   
        }
               
    }
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        
        perfil.setVisible(true);
        this.dispose();
        usuario();
    }//GEN-LAST:event_btnPerfilActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraductorlogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraductorlogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraductorlogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraductorlogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraductorlogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JToggleButton btnTraduccir;
    private javax.swing.JComboBox<String> cbxelegiridima;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTraduccion;
    public javax.swing.JLabel lblnombresUT;
    public javax.swing.JLabel lblusuarioT;
    private javax.swing.JTable tableTrad;
    private javax.swing.JTextField txtPalabraIngreso;
    // End of variables declaration//GEN-END:variables

    public int comboBox(){
        int num=cbxelegiridima.getSelectedIndex();
        if (num==0) {
            return 0;
        } else {
            if (num==1) {
                return 1;
            } else {
                return 2;
            }
        }
    }
    
    
    public void Es_Ki(){
        String camb=txtPalabraIngreso.getText().toLowerCase();
        String nw=cleanString(camb);
        String cnw=nw.replace("ñ","~n");//esto aun no funciona 
        System.out.println(cnw);
        String codigo="SELECT codpalabra2 From palabra1 WHERE palabra1p='"+cnw+"'";
        
            ResultSet rsc,rsp;
            ConsultasSQL con = new ConsultasSQL(conecto.getCon(), codigo);
            
            if(con.getError()==null){
                rsc=con.getResultado();
                try {
                    rsc.next();
                    String coigo2 = rsc.getString("codpalabra2");
                    String palabra="SELECT palabra2p FROM palabra2 WHERE codPalabra2='"+coigo2+"'";
                    ConsultasSQL pal=new ConsultasSQL(conecto.getCon(), palabra);
                    rsp=pal.getResultado();
                    rsp.next();
                    String palabraesp = rsp.getString("palabra2p");
                    lblTraduccion.setText(palabraesp);  
                   rsp.close();  
                } catch (SQLException ex) {
                    ex.getMessage();
                    lblTraduccion.setText(txtPalabraIngreso.getText());
                }
                
               
            }
    }
    
    public void Ki_Es(){
        String camb=txtPalabraIngreso.getText().toLowerCase();
        String nw=cleanString(camb);
        String cnw=nw.replace("ñ","~n");//esto aun no funciona 
        System.out.println(cnw);
        String codigo="SELECT codPalabra2 FROM palabra2 WHERE palabra2p='"+cnw+"'";
        
            ResultSet rsc,rsp;
            ConsultasSQL con = new ConsultasSQL(conecto.getCon(), codigo);
            
            if(con.getError()==null){
                rsc=con.getResultado();
                try {
                    rsc.next();
                    String coigo2 = rsc.getString("codPalabra2");
                    String palabra="SELECT palabra1p FROM palabra1 WHERE codpalabra2='"+coigo2+"'";
                    ConsultasSQL pal=new ConsultasSQL(conecto.getCon(), palabra);
                    rsp=pal.getResultado();
                    rsp.next();
                    String palabraesp = rsp.getString("palabra1p");
                    lblTraduccion.setText(palabraesp);
                } catch (SQLException ex) {
                    ex.getMessage();
                    lblTraduccion.setText(txtPalabraIngreso.getText());
                }
            }
    }
    
    public void usuario(){
        try {
            System.out.println(lblnombresUT.getText());
            String sql="SELECT usuario FROM persona WHERE usuario LIKE'"+lblusuarioT.getText()+"'";
            ResultSet rs=conecto.query(sql);
            if(rs.next()){
                
                String usuario=rs.getString("usuario");
                System.out.println(usuario);
                perfil.lblUsuarioJ.setText(usuario);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(TraductorlogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
}
